services:
  filler:
    build: .
    environment:
      WALLET_MNEMONIC: ${WALLET_MNEMONIC}
      COINGECKO_API_KEY: ${COINGECKO_API_KEY}
      TRADER_SET: ${TRADER_SET}
    # extra_hosts:
    #   - "host.docker.internal:host-gateway"
    volumes:
      - ./config.testnet.json:/root/config.testnet.json
